###################
###################

## Jekyll Build ##
## Due to Netlify changing its system, decided to host our Jekyll sites ourselves ##

## This builds the jekyll site inside Ubuntu and allows us to push the result to our server via SSH ##

###################
###################

## Name ##
## Builds Jekyll sites on push (locally) and then sends the compiled payload to our server ##
name: Jekyll Build

## Push ##
## Only trigger when 'main' branch is updated ##
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Jobs ##
## Need to install Ruby, Jekyll, Bundler and run the build as required ##
jobs:

  ###########
  ## Build ##
  ###########
  
  ## Single job to install Jekyll and run it ##
  build:
  
    ## Name ##
    name: Build (Jekyll)
  
    ## OS ##
    runs-on: ubuntu-latest

    ## Steps ##
    ## Required to complete the job ##
    steps:
    
      ## Repo ##
      ## Pulls the latest files for the repo ##
      - uses: actions/checkout@v3

      ## Ruby ##
      ## Install Ruby ##
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      ## Bundle ##
      ## Installs the gems present in the repo's Gemfile ##
      - name: Bundle
        run: bundle install
        
      ## Jekyll ##
      ## Run the 'jekyll build' command and output the result to /dist ##
      - name: Jekyll build
        run: jekyll build --destination dist
        
      ## Artifacts ##
      ## Add dist to artifacts (so we can download it later if needed) ##
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/**/*
          
      ## Release ##
      ## Create release of Jekyll site so that we're able to reference it as needed in the future ##
      - uses: softprops/action-gh-release@v1
        with:
          name: test
          tag_name: test
          draft: false
          prerelease: false
          generate_release_notes: false
          body: |
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          files: ./dist
          
  ############
  ## Deploy ##
  ############
  
  ## Deploy the built code to the web server ##
  deploy:
  
    ## Name ##
    name: Deploy (Push Jekyll Dist to Server)
    
    ## Needs ##
    ## This is required to provide the information ##
    needs: build
      
    ## OS ##
    runs-on: ubuntu-latest

    ## Steps ##
    ## Required to complete the job ##
    steps:
    
      ## Artifact ##
      ## Because the new job spins up a new VM instance, we need to repopulate the distributed files ##
      - uses: actions/download-artifact@v3
        with:
          name: dist
          
      - run: ls -la
    

      
      
        
    
